#!/usr/bin/env bun
/**
 * build-candidate-manifest.ts — Normalize extracted fingerprints into candidate manifests.
 *
 * Usage:
 *   bun scripts/analysis/build-candidate-manifest.ts <fingerprint.json> --version <ver> [--output <dir>] [--tarball-hash <sha256>]
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { extname, join, resolve } from "node:path";
import { createProgress } from "../lib/progress.ts";

import { classifyRisk, validateCandidateManifest } from "../../src/fingerprint/schema.ts";
import type {
    CandidateManifest,
    ConfidenceLevel,
    FieldMetadata,
    FieldOrigin,
    ManifestIndex,
    ManifestIndexEntry,
} from "../../src/fingerprint/types.ts";
import { extractFingerprint } from "./extract-fingerprint.ts";
import type { Fingerprint } from "./types.ts";

const DEFAULT_OUTPUT_DIR = resolve(process.cwd(), "manifests/candidate/claude-code");
const DEFAULT_TARBALL_HASH = "unknown";
const NPM_PACKAGE = "@anthropic-ai/claude-code";
const TARBALL_BASE_URL = "https://registry.npmjs.org/@anthropic-ai/claude-code/-";

interface ParsedArgs {
    fingerprintPath: string;
    version: string;
    outputDir: string;
    tarballHash: string;
    help: boolean;
}

function printUsage(): void {
    console.log(`Usage: bun scripts/analysis/build-candidate-manifest.ts <fingerprint.json> --version <ver> [--output <dir>] [--tarball-hash <sha256>]

Arguments:
  <fingerprint.json>         Path to JSON generated by extract-fingerprint.ts

Options:
  --version <ver>            Claude Code version to persist in the manifest
  --output <dir>             Output directory for <version>.json + index.json
                             Default: manifests/candidate/claude-code
  --tarball-hash <sha256>    Optional tarball hash for source metadata
  --help                     Show this help message
`);
}

export function parseArgs(args: string[]): ParsedArgs {
    let fingerprintPath = "";
    let version = "";
    let outputDir = DEFAULT_OUTPUT_DIR;
    let tarballHash = DEFAULT_TARBALL_HASH;
    let help = false;

    for (let index = 0; index < args.length; index += 1) {
        const arg = args[index];
        if (arg === "--help") {
            help = true;
        } else if (arg === "--version" && index + 1 < args.length) {
            version = args[index + 1];
            index += 1;
        } else if (arg === "--output" && index + 1 < args.length) {
            outputDir = resolve(args[index + 1]);
            index += 1;
        } else if (arg === "--tarball-hash" && index + 1 < args.length) {
            tarballHash = args[index + 1].trim() || DEFAULT_TARBALL_HASH;
            index += 1;
        } else if (!arg.startsWith("--") && !fingerprintPath) {
            fingerprintPath = resolve(arg);
        }
    }

    if (!help && !fingerprintPath) {
        throw new Error("Missing required <fingerprint.json> argument");
    }

    return {
        fingerprintPath,
        version,
        outputDir,
        tarballHash,
        help,
    };
}

function readJsonFile<T>(filePath: string): T {
    try {
        return JSON.parse(readFileSync(filePath, "utf8")) as T;
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        throw new Error(`Failed to read JSON from ${filePath}: ${message}`);
    }
}

function readFingerprintInput(filePath: string, versionOverride: string): Fingerprint {
    if (extname(filePath).toLowerCase() === ".json") {
        return readJsonFile<Fingerprint>(filePath);
    }

    const source = readFileSync(filePath, "utf8");
    const inferredVersion = versionOverride || filePath.match(/cli-([0-9]+\.[0-9]+\.[0-9]+)\.js$/)?.[1] || "unknown";
    return extractFingerprint(source, inferredVersion);
}

function uniqueStrings(values: Array<string | null | undefined>): string[] {
    return [
        ...new Set(values.filter((value): value is string => typeof value === "string" && value.trim().length > 0)),
    ];
}

function compareVersions(left: string, right: string): number {
    const leftParts = left.split(".").map((part) => Number.parseInt(part, 10));
    const rightParts = right.split(".").map((part) => Number.parseInt(part, 10));
    const maxLength = Math.max(leftParts.length, rightParts.length);

    for (let index = 0; index < maxLength; index += 1) {
        const leftPart = leftParts[index] ?? 0;
        const rightPart = rightParts[index] ?? 0;
        if (leftPart !== rightPart) {
            return leftPart - rightPart;
        }
    }

    return 0;
}

function createFieldMetadata<T>(
    fieldPath: string,
    value: T,
    extractedAt: string,
    options: {
        origin: FieldOrigin;
        confidence?: ConfidenceLevel;
    },
): FieldMetadata<T> {
    return {
        value,
        risk: classifyRisk(fieldPath),
        origin: options.origin,
        confidence: options.confidence ?? (options.origin === "bundle-string" ? "high" : "medium"),
        extractedAt,
    };
}

function hasBundleString(value: unknown): boolean {
    if (typeof value === "string") {
        return value.trim().length > 0;
    }

    if (Array.isArray(value)) {
        return value.length > 0;
    }

    if (typeof value === "object" && value !== null) {
        return Object.keys(value as Record<string, unknown>).length > 0;
    }

    return Boolean(value);
}

function createSource(version: string, extractionTimestamp: string, tarballHash: string) {
    return {
        npmPackage: NPM_PACKAGE,
        tarballUrl: `${TARBALL_BASE_URL}claude-code-${version}.tgz`,
        tarballHash,
        extractionTimestamp,
    };
}

function buildParserWarnings(fingerprint: Fingerprint, tarballHash: string): string[] {
    const warnings: string[] = [];

    if (tarballHash === DEFAULT_TARBALL_HASH) {
        warnings.push("tarballHash not provided; stored as 'unknown'.");
    }
    if (!fingerprint.headers.userAgent.template) {
        warnings.push("No user-agent template was extracted; fell back to a version-based heuristic.");
    }
    if (Object.keys(fingerprint.headers.stainlessHeaders).length === 0) {
        warnings.push("No x-stainless-* headers were extracted; candidate defaults rely on heuristics.");
    }
    if (!fingerprint.betas.oauthBeta && fingerprint.betas.oauthBetas.length === 0) {
        warnings.push("No OAuth beta marker was extracted; required auth betas rely on defaults.");
    }
    if (!fingerprint.billing.cch && fingerprint.billing.hashPositions.length === 0 && !fingerprint.billing.template) {
        warnings.push("Billing hash evidence was incomplete; cchStrategy relies on a heuristic classification.");
    }
    if (!fingerprint.oauth.pkce.hasCodeChallenge && !fingerprint.oauth.pkce.hasCodeVerifier) {
        warnings.push("PKCE markers were not found; authHeaderMode remains a heuristic.");
    }

    return warnings;
}

function buildUnknownFields(fingerprint: Fingerprint): string[] {
    const knownTopLevelFields = new Set(["version", "extractedAt", "oauth", "headers", "betas", "billing"]);
    return Object.keys(fingerprint).filter((key) => !knownTopLevelFields.has(key));
}

export function buildCandidateManifest(
    fingerprint: Fingerprint,
    version: string,
    tarballHash: string,
): CandidateManifest {
    const extractedAt = fingerprint.extractedAt || new Date().toISOString();
    const requiredBaseBetas = uniqueStrings([
        ...fingerprint.betas.oauthBetas,
        fingerprint.betas.oauthBeta,
        ...fingerprint.betas.betas.filter((beta) => beta.startsWith("oauth-")),
    ]);
    const stableBaseBetas = requiredBaseBetas.length > 0 ? requiredBaseBetas : ["oauth-2025-04-20"];
    const optionalBetas = fingerprint.betas.betas.filter((beta) => !stableBaseBetas.includes(beta));
    const stainlessHeaders = Object.fromEntries(
        Object.entries(fingerprint.headers.stainlessHeaders).filter(
            ([, value]) => typeof value === "string" && value.length > 0,
        ),
    ) as Record<string, string>;

    const manifest: CandidateManifest = {
        version,
        source: createSource(version, extractedAt, tarballHash),
        transport: {
            pathStyle: createFieldMetadata("transport.pathStyle", "/v1/messages?beta=true", extractedAt, {
                origin: "bundle-heuristic",
                confidence: "medium",
            }),
            defaultHeaders: createFieldMetadata(
                "transport.defaultHeaders",
                {
                    "content-type": "application/json",
                    "anthropic-version": "2023-06-01",
                    "anthropic-dangerous-direct-browser-access": "true",
                },
                extractedAt,
                {
                    origin: "bundle-heuristic",
                    confidence: "medium",
                },
            ),
            authHeaderMode: createFieldMetadata("transport.authHeaderMode", "bearer", extractedAt, {
                origin: "bundle-heuristic",
                confidence:
                    fingerprint.oauth.pkce.hasCodeChallenge || fingerprint.oauth.pkce.hasCodeVerifier
                        ? "high"
                        : "medium",
            }),
        },
        headers: {
            userAgent: createFieldMetadata(
                "headers.userAgent",
                fingerprint.headers.userAgent.template ?? `claude-cli/${version}`,
                extractedAt,
                {
                    origin: hasBundleString(fingerprint.headers.userAgent.template)
                        ? "bundle-string"
                        : "bundle-heuristic",
                    confidence: fingerprint.headers.userAgent.template ? "high" : "medium",
                },
            ),
            xApp: createFieldMetadata("headers.xApp", "cli", extractedAt, {
                origin: "bundle-heuristic",
                confidence: "medium",
            }),
            xStainlessHeaders: createFieldMetadata("headers.xStainlessHeaders", stainlessHeaders, extractedAt, {
                origin: Object.keys(stainlessHeaders).length > 0 ? "bundle-string" : "bundle-heuristic",
                confidence: Object.keys(stainlessHeaders).length > 0 ? "high" : "low",
            }),
            xClientRequestId: createFieldMetadata("headers.xClientRequestId", "x-client-request-id", extractedAt, {
                origin: "bundle-heuristic",
                confidence: "medium",
            }),
            xClaudeCodeSessionId: createFieldMetadata(
                "headers.xClaudeCodeSessionId",
                "X-Claude-Code-Session-Id",
                extractedAt,
                {
                    origin: "bundle-heuristic",
                    confidence: "medium",
                },
            ),
        },
        betas: {
            requiredBaseBetas: createFieldMetadata("betas.requiredBaseBetas", stableBaseBetas, extractedAt, {
                origin: requiredBaseBetas.length > 0 ? "bundle-string" : "bundle-heuristic",
                confidence: requiredBaseBetas.length > 0 ? "high" : "medium",
            }),
            optionalBetas: createFieldMetadata("betas.optionalBetas", optionalBetas, extractedAt, {
                origin: optionalBetas.length > 0 ? "bundle-string" : "bundle-heuristic",
                confidence: optionalBetas.length > 0 ? "high" : "medium",
            }),
            authModeBetas: createFieldMetadata("betas.authModeBetas", stableBaseBetas, extractedAt, {
                origin: requiredBaseBetas.length > 0 ? "bundle-string" : "bundle-heuristic",
                confidence: requiredBaseBetas.length > 0 ? "high" : "medium",
            }),
        },
        billing: {
            ccVersion: createFieldMetadata("billing.ccVersion", version, extractedAt, {
                origin: "bundle-heuristic",
                confidence: "high",
            }),
            ccEntrypoint: createFieldMetadata("billing.ccEntrypoint", "cli", extractedAt, {
                origin: "bundle-heuristic",
                confidence: "medium",
            }),
            cchStrategy: createFieldMetadata(
                "billing.cchStrategy",
                fingerprint.billing.cch || fingerprint.billing.template || fingerprint.billing.hashPositions.length > 0
                    ? "xxhash64-5hex"
                    : "xxhash64",
                extractedAt,
                {
                    origin:
                        fingerprint.billing.cch ||
                        fingerprint.billing.template ||
                        fingerprint.billing.hashPositions.length > 0
                            ? "bundle-string"
                            : "bundle-heuristic",
                    confidence:
                        fingerprint.billing.cch ||
                        fingerprint.billing.template ||
                        fingerprint.billing.hashPositions.length > 0
                            ? "medium"
                            : "low",
                },
            ),
        },
        body: {
            defaultStream: createFieldMetadata("body.defaultStream", true, extractedAt, {
                origin: "bundle-heuristic",
                confidence: "medium",
            }),
            defaultMaxTokens: createFieldMetadata("body.defaultMaxTokens", 4096, extractedAt, {
                origin: "bundle-heuristic",
                confidence: "medium",
            }),
            temperaturePresence: createFieldMetadata("body.temperaturePresence", false, extractedAt, {
                origin: "bundle-heuristic",
                confidence: "low",
            }),
            thinkingKey: createFieldMetadata("body.thinkingKey", true, extractedAt, {
                origin: "bundle-heuristic",
                confidence: "low",
            }),
            contextManagementKey: createFieldMetadata("body.contextManagementKey", true, extractedAt, {
                origin: "bundle-heuristic",
                confidence: "low",
            }),
            toolsKey: createFieldMetadata("body.toolsKey", true, extractedAt, {
                origin: "bundle-heuristic",
                confidence: "low",
            }),
        },
        prompt: {
            identityString: createFieldMetadata(
                "prompt.identityString",
                "You are Claude Code, Anthropic's official CLI for Claude.",
                extractedAt,
                {
                    origin: "bundle-heuristic",
                    confidence: "medium",
                },
            ),
            billingBlockPlacement: createFieldMetadata("prompt.billingBlockPlacement", "prepend", extractedAt, {
                origin: "bundle-heuristic",
                confidence: "medium",
            }),
            appendMode: createFieldMetadata("prompt.appendMode", false, extractedAt, {
                origin: "bundle-heuristic",
                confidence: "low",
            }),
            cacheControlBehavior: createFieldMetadata(
                "prompt.cacheControlBehavior",
                "ephemeral-identity-block",
                extractedAt,
                {
                    origin: "bundle-heuristic",
                    confidence: "low",
                },
            ),
        },
        metadata: {
            userIdShape: createFieldMetadata(
                "metadata.userIdShape",
                "user_<persistentUserId>_account_<accountId>_session_<sessionId>",
                extractedAt,
                {
                    origin: "bundle-heuristic",
                    confidence: "low",
                },
            ),
            deviceLinkage: createFieldMetadata("metadata.deviceLinkage", "persistentUserId", extractedAt, {
                origin: "bundle-heuristic",
                confidence: "low",
            }),
            accountLinkage: createFieldMetadata("metadata.accountLinkage", "accountUuid-or-id", extractedAt, {
                origin: "bundle-heuristic",
                confidence: "low",
            }),
        },
        parserWarnings: buildParserWarnings(fingerprint, tarballHash),
        unknownFields: buildUnknownFields(fingerprint),
    };

    return validateCandidateManifest(manifest);
}

function createEmptyIndex(timestamp: string): ManifestIndex {
    return {
        schemaVersion: "1.0.0",
        lastUpdated: timestamp,
        versions: [],
        latest: null,
    };
}

function loadManifestIndex(indexPath: string, timestamp: string): ManifestIndex {
    if (!existsSync(indexPath)) {
        return createEmptyIndex(timestamp);
    }

    const index = readJsonFile<ManifestIndex>(indexPath);
    return {
        schemaVersion: index.schemaVersion || "1.0.0",
        lastUpdated: index.lastUpdated || timestamp,
        versions: Array.isArray(index.versions) ? index.versions : [],
        latest: typeof index.latest === "string" ? index.latest : null,
    };
}

export function updateManifestIndex(index: ManifestIndex, version: string, createdAt: string): ManifestIndex {
    const remainingEntries = index.versions.filter((entry) => entry.version !== version);
    const existingEntry = index.versions.find((entry) => entry.version === version);
    const nextEntry: ManifestIndexEntry = {
        version,
        path: `${version}.json`,
        createdAt: existingEntry?.createdAt ?? createdAt,
    };

    const versions = [...remainingEntries, nextEntry].sort((left, right) =>
        compareVersions(right.version, left.version),
    );

    return {
        schemaVersion: index.schemaVersion || "1.0.0",
        lastUpdated: createdAt,
        versions,
        latest: versions[0]?.version ?? null,
    };
}

async function main(): Promise<void> {
    const parsedArgs = parseArgs(process.argv.slice(2));

    if (parsedArgs.help) {
        printUsage();
        return;
    }

    const progress = createProgress();

    progress.startStep("read fingerprint", parsedArgs.fingerprintPath);
    const fingerprint = readFingerprintInput(parsedArgs.fingerprintPath, parsedArgs.version);
    const version = parsedArgs.version || fingerprint.version;
    if (!version) {
        progress.fail("version could not be determined");
        throw new Error("Unable to determine manifest version; pass --version or provide fingerprint.version");
    }
    progress.finishStep(version);

    progress.startStep("build candidate manifest");
    const manifest = buildCandidateManifest(fingerprint, version, parsedArgs.tarballHash);
    progress.finishStep(
        `${manifest.parserWarnings.length} warning(s), ${manifest.unknownFields.length} unknown field(s)`,
    );

    progress.startStep("write manifest");
    mkdirSync(parsedArgs.outputDir, { recursive: true });
    const manifestPath = join(parsedArgs.outputDir, `${version}.json`);
    const indexPath = join(parsedArgs.outputDir, "index.json");
    writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");

    const index = updateManifestIndex(
        loadManifestIndex(indexPath, manifest.source.extractionTimestamp),
        version,
        new Date().toISOString(),
    );
    writeFileSync(indexPath, `${JSON.stringify(index, null, 2)}\n`, "utf8");
    progress.finishStep(manifestPath);

    progress.done();

    console.log(
        JSON.stringify(
            {
                version,
                manifestPath,
                indexPath,
                parserWarningCount: manifest.parserWarnings.length,
                unknownFieldCount: manifest.unknownFields.length,
            },
            null,
            2,
        ),
    );
}

if (import.meta.main) {
    main().catch((error) => {
        console.error(`Error: ${error instanceof Error ? error.message : String(error)}`);
        process.exit(1);
    });
}
