/**
 * proxy-capture.mjs (validation copy)
 *
 * Adapted from .omc/research/proxy-capture.mjs to use env-var-configurable
 * paths so validation runs do not clobber the historical cch-captures.md.
 *
 * Defaults write to scripts/validation/cch-validation-2026-04-11.md and
 * generate certs in scripts/validation/proxy-certs/ (separate from the
 * historical .omc/research/proxy-certs/ used by the prior session).
 *
 * Env vars:
 *   CCH_CAPTURES_FILE   absolute path for capture markdown (default: dated file in this dir)
 *   CCH_CERT_DIR        absolute path for ephemeral CA + server certs (default: ./proxy-certs in this dir)
 *   CCH_LISTEN_PORT     proxy listen port (default: 9091)
 *
 * Run:
 *   bun scripts/validation/proxy-capture.mjs
 *   # then in another terminal, set HTTPS_PROXY=http://127.0.0.1:9091 and run claude
 */
import http from "node:http";
import tls from "node:tls";
import fs from "node:fs";
import { execFileSync } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const LISTEN_PORT = parseInt(process.env.CCH_LISTEN_PORT ?? "9091", 10);
const CAPTURES_FILE = process.env.CCH_CAPTURES_FILE ?? path.join(__dirname, "cch-validation-2026-04-11.md");
const CERT_DIR = process.env.CCH_CERT_DIR ?? path.join(__dirname, "proxy-certs");

function ensureCerts() {
  if (!fs.existsSync(CERT_DIR)) fs.mkdirSync(CERT_DIR, { recursive: true });
  const caKey = path.join(CERT_DIR, "ca.key");
  const caCert = path.join(CERT_DIR, "ca.crt");
  const srvKey = path.join(CERT_DIR, "srv.key");
  const srvCert = path.join(CERT_DIR, "srv.crt");
  const srvCsr = path.join(CERT_DIR, "srv.csr");
  const extCnf = path.join(CERT_DIR, "ext.cnf");

  if (!fs.existsSync(caKey)) {
    console.log(`[proxy] Generating ephemeral CA in ${CERT_DIR}`);
    execFileSync("openssl", ["genrsa", "-out", caKey, "2048"]);
    execFileSync("openssl", [
      "req",
      "-new",
      "-x509",
      "-days",
      "365",
      "-key",
      caKey,
      "-out",
      caCert,
      "-subj",
      "/CN=ProxyCapture-Validation CA",
    ]);
    execFileSync("openssl", ["genrsa", "-out", srvKey, "2048"]);
    execFileSync("openssl", ["req", "-new", "-key", srvKey, "-out", srvCsr, "-subj", "/CN=api.anthropic.com"]);
    fs.writeFileSync(extCnf, "[ext]\nsubjectAltName=DNS:*.anthropic.com,DNS:api.anthropic.com\n");
    execFileSync("openssl", [
      "x509",
      "-req",
      "-days",
      "365",
      "-in",
      srvCsr,
      "-CA",
      caCert,
      "-CAkey",
      caKey,
      "-CAcreateserial",
      "-out",
      srvCert,
      "-extfile",
      extCnf,
      "-extensions",
      "ext",
    ]);
  }
  return {
    key: fs.readFileSync(srvKey),
    cert: fs.readFileSync(srvCert),
  };
}

let captureCount = 0;

function writeCapture({ method, url, headers, bodySnippet }) {
  captureCount++;
  const ts = new Date().toISOString();
  const cch = headers["x-anthropic-cch"] || "(not in headers)";

  // cch is sent in request BODY as a text block: "x-anthropic-billing-header: ...; cch=XXXXX;"
  let billingHeader = "(not found in body)";
  let cchFromBody = null;
  if (bodySnippet) {
    const billingMatch = bodySnippet.match(/x-anthropic-billing-header:[^"\\]*/);
    if (billingMatch) billingHeader = billingMatch[0];
    const cchMatch = bodySnippet.match(/cch=([0-9a-f]{5})/);
    if (cchMatch) cchFromBody = cchMatch[1];
  }

  // Only log /v1/messages and other API calls (skip telemetry noise)
  const isApiCall = url.includes("/v1/") || url.includes("/api/");
  if (!isApiCall) return;

  let entry = `\n## Capture #${captureCount} — ${ts}\n\n`;
  entry += `**Method/URL:** \`${method} ${url}\`\n\n`;
  entry += `**x-anthropic-cch (header):** \`${cch}\`\n\n`;
  if (cchFromBody) entry += `**cch (from body):** \`${cchFromBody}\` *** FOUND ***\n\n`;
  entry += `**billing-header (from body):** \`${billingHeader}\`\n\n`;
  entry += `**All anthropic request headers:**\n\`\`\`\n`;
  for (const [k, v] of Object.entries(headers)) {
    if (k.toLowerCase().startsWith("x-anthropic") || k.toLowerCase().startsWith("anthropic")) {
      entry += `${k}: ${v}\n`;
    }
  }
  entry += `\`\`\`\n`;
  if (bodySnippet && cchFromBody) {
    // Only log full body when cch found
    entry += `\n**Full request body:**\n\`\`\`json\n${bodySnippet}\n\`\`\`\n`;
  }
  entry += `\n---\n`;

  fs.appendFileSync(CAPTURES_FILE, entry);
  const marker = cchFromBody ? ` *** CCH=${cchFromBody} ***` : "";
  console.log(`[proxy] #${captureCount}${marker}  ${method} ${url}`);
}

// Initialize captures file (overwrite — but only the validation file, not the historical one)
fs.writeFileSync(
  CAPTURES_FILE,
  `# CCH Validation Captures — ${new Date().toISOString()}\n\nGenerated by scripts/validation/proxy-capture.mjs\n\nThis file is for the cch validation run. The historical cch-captures.md from CC 2.1.98 lives at .omc/research/cch-captures.md and is not touched.\n`,
);

const certs = ensureCerts();

const server = http.createServer((req, res) => {
  res.writeHead(200);
  res.end("proxy ok");
});

server.on("connect", (req, clientSocket, _head) => {
  const [hostname, portStr] = (req.headers.host || req.url).split(":");
  const port = parseInt(portStr || "443", 10);
  console.log(`[proxy] CONNECT ${hostname}:${port}`);

  clientSocket.write("HTTP/1.1 200 Connection established\r\n\r\n");

  const tlsSocket = new tls.TLSSocket(clientSocket, {
    isServer: true,
    key: certs.key,
    cert: certs.cert,
    rejectUnauthorized: false,
  });

  let rawBuf = Buffer.alloc(0);
  let state = "headers"; // 'headers' | 'body' | 'done'
  let method = "",
    reqPath = "";
  const hdrs = {};
  let contentLength = 0;
  let headerEndIdx = 0;
  let upstream = null;

  tlsSocket.on("error", (e) => console.error("[proxy] client tls:", e.message));

  function startUpstream() {
    if (upstream) return;
    upstream = tls.connect({ host: hostname, port, rejectUnauthorized: false }, () => {
      upstream.write(rawBuf);
    });
    upstream.on("error", (e) => console.error("[proxy] upstream:", e.message));
    upstream.pipe(tlsSocket);
    // Pipe any future client data directly
    tlsSocket.on("data", (chunk) => upstream.write(chunk));
  }

  function processFirstRequest() {
    const bodyBuf = rawBuf.slice(headerEndIdx);
    // Check if we have full body
    if (contentLength > 0 && bodyBuf.length < contentLength) return false; // need more data
    const bodySnippet = bodyBuf.length > 0 ? bodyBuf.toString("utf8", 0, 100000) : null;
    writeCapture({
      method,
      url: `https://${hostname}:${port}${reqPath}`,
      headers: hdrs,
      bodySnippet,
    });
    return true;
  }

  // Buffer only the first request, then hand off
  const firstDataHandler = (chunk) => {
    if (state === "done") return;
    rawBuf = Buffer.concat([rawBuf, chunk]);

    if (state === "headers") {
      const s = rawBuf.toString("binary");
      const sep = s.indexOf("\r\n\r\n");
      if (sep === -1) return;

      const headerSection = s.slice(0, sep);
      const lines = headerSection.split("\r\n");
      [method, reqPath] = lines[0].split(" ");
      for (const line of lines.slice(1)) {
        const ci = line.indexOf(":");
        if (ci > 0) hdrs[line.slice(0, ci).trim().toLowerCase()] = line.slice(ci + 1).trim();
      }
      contentLength = parseInt(hdrs["content-length"] || "0", 10);
      headerEndIdx = Buffer.byteLength(headerSection, "binary") + 4;
      state = "body";
    }

    if (state === "body") {
      if (processFirstRequest()) {
        state = "done";
        tlsSocket.removeListener("data", firstDataHandler);
        startUpstream();
      }
    }
  };

  tlsSocket.on("data", firstDataHandler);
});

server.listen(LISTEN_PORT, "127.0.0.1", () => {
  console.log(`[proxy] Ready on 127.0.0.1:${LISTEN_PORT}  captures -> ${CAPTURES_FILE}`);
  console.log(`[proxy] Cert dir: ${CERT_DIR}`);
  console.log(
    `[proxy] To capture CC: HTTPS_PROXY=http://127.0.0.1:${LISTEN_PORT} BUN_TLS_REJECT_UNAUTHORIZED=0 NODE_TLS_REJECT_UNAUTHORIZED=0 claude --print "<prompt>"`,
  );
});
