#!/usr/bin/env bun

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { validateCandidateManifest, validateVerifiedManifest } from "../../src/fingerprint/schema.ts";
import type {
    CandidateManifest,
    FieldMetadata,
    ManifestIndex,
    ManifestIndexEntry,
    RejectedField,
    VerificationReport,
    VerifiedField,
    VerifiedManifest,
} from "../../src/fingerprint/types.ts";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(SCRIPT_DIR, "../..");
const DEFAULT_CANDIDATE_DIR = resolve(REPO_ROOT, "manifests/candidate/claude-code");
const DEFAULT_VERIFIED_DIR = resolve(REPO_ROOT, "manifests/verified/claude-code");

interface ParsedArgs {
    version: string;
    reportPath: string;
    candidatePath: string;
    verifiedDir: string;
    verifiedBy?: string;
    onlyPaths: Set<string>;
    help: boolean;
}

interface FieldDecision {
    promoted: VerifiedField[];
    rejected: RejectedField[];
}

function printUsage(): void {
    console.log(`Usage: bun scripts/verification/promote-verified.ts --version <ver> --report <verification-report.json>

Promotes candidate manifest fields into manifests/verified/claude-code/<version>.json
when the live verification report proves that the candidate value matches the
observed sanitized wire value.

Options:
  --version <ver>            Candidate/verified manifest version
  --report <path>            Verification report generated by run-live-verification.ts
  --candidate <path>         Candidate manifest path
                            Default: manifests/candidate/claude-code/<version>.json
  --verified-dir <path>      Verified manifest directory
                            Default: manifests/verified/claude-code
  --verified-by <label>      Override report.verifiedBy in the output manifest
  --only-field <path[,path]> Promote only the selected verified field path(s)
                            Repeat the flag or pass comma-separated values
  --help                     Show this help message
`);
}

function splitFieldPaths(value: string): string[] {
    return value
        .split(",")
        .map((entry) => entry.trim())
        .filter(Boolean);
}

export function parseArgs(args: string[]): ParsedArgs {
    let version = "";
    let reportPath = "";
    let candidatePath = "";
    let verifiedDir = DEFAULT_VERIFIED_DIR;
    let verifiedBy: string | undefined;
    let help = false;
    const onlyPaths = new Set<string>();

    for (let index = 0; index < args.length; index += 1) {
        const arg = args[index];
        if (arg === "--help") {
            help = true;
            continue;
        }
        if (arg === "--version" && index + 1 < args.length) {
            version = args[index + 1] ?? "";
            index += 1;
            continue;
        }
        if (arg === "--report" && index + 1 < args.length) {
            reportPath = resolve(args[index + 1] ?? "");
            index += 1;
            continue;
        }
        if (arg === "--candidate" && index + 1 < args.length) {
            candidatePath = resolve(args[index + 1] ?? "");
            index += 1;
            continue;
        }
        if (arg === "--verified-dir" && index + 1 < args.length) {
            verifiedDir = resolve(args[index + 1] ?? "");
            index += 1;
            continue;
        }
        if (arg === "--verified-by" && index + 1 < args.length) {
            verifiedBy = args[index + 1] ?? "";
            index += 1;
            continue;
        }
        if (arg === "--only-field" && index + 1 < args.length) {
            for (const path of splitFieldPaths(args[index + 1] ?? "")) {
                onlyPaths.add(path);
            }
            index += 1;
            continue;
        }
    }

    if (!help && !version.trim()) {
        throw new Error("Missing required --version <ver>");
    }
    if (!help && !reportPath) {
        throw new Error("Missing required --report <verification-report.json>");
    }

    return {
        version: version.trim(),
        reportPath,
        candidatePath: candidatePath || resolve(DEFAULT_CANDIDATE_DIR, `${version}.json`),
        verifiedDir,
        verifiedBy: verifiedBy?.trim() || undefined,
        onlyPaths,
        help,
    };
}

function readJsonFile<T>(filePath: string): T {
    try {
        return JSON.parse(readFileSync(filePath, "utf8")) as T;
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        throw new Error(`Failed to read JSON from ${filePath}: ${message}`);
    }
}

function stableStringify(value: unknown): string {
    if (Array.isArray(value)) {
        return JSON.stringify(value.map((item) => JSON.parse(stableStringify(item))));
    }
    if (typeof value === "object" && value !== null) {
        const entries = Object.entries(value as Record<string, unknown>)
            .sort(([left], [right]) => left.localeCompare(right))
            .map(([key, entryValue]) => [key, JSON.parse(stableStringify(entryValue))]);
        return JSON.stringify(Object.fromEntries(entries));
    }
    return JSON.stringify(value);
}

export function flattenCandidateFields(manifest: CandidateManifest): Map<string, FieldMetadata<unknown>> {
    const flat = new Map<string, FieldMetadata<unknown>>();
    const roots = {
        transport: manifest.transport,
        headers: manifest.headers,
        betas: manifest.betas,
        billing: manifest.billing,
        body: manifest.body,
        prompt: manifest.prompt,
        metadata: manifest.metadata,
    } as Record<string, unknown>;

    for (const [root, value] of Object.entries(roots)) {
        flattenFieldMetadata(root, value, flat);
    }

    return flat;
}

function flattenFieldMetadata(path: string, value: unknown, flat: Map<string, FieldMetadata<unknown>>): void {
    if (!value || typeof value !== "object") {
        return;
    }

    const maybeField = value as Record<string, unknown>;
    if (
        Object.prototype.hasOwnProperty.call(maybeField, "value") &&
        Object.prototype.hasOwnProperty.call(maybeField, "risk") &&
        Object.prototype.hasOwnProperty.call(maybeField, "origin")
    ) {
        flat.set(path, maybeField as unknown as FieldMetadata<unknown>);
        return;
    }

    for (const [key, nested] of Object.entries(maybeField)) {
        flattenFieldMetadata(`${path}.${key}`, nested, flat);
    }
}

function compareVersions(left: string, right: string): number {
    const leftParts = left.split(".").map((part) => Number.parseInt(part, 10));
    const rightParts = right.split(".").map((part) => Number.parseInt(part, 10));
    const maxLength = Math.max(leftParts.length, rightParts.length);
    for (let index = 0; index < maxLength; index += 1) {
        const leftPart = leftParts[index] ?? 0;
        const rightPart = rightParts[index] ?? 0;
        if (leftPart !== rightPart) {
            return leftPart - rightPart;
        }
    }
    return 0;
}

function createEmptyIndex(timestamp: string): ManifestIndex {
    return {
        schemaVersion: "1.0.0",
        lastUpdated: timestamp,
        versions: [],
        latest: null,
    };
}

function readExistingVerifiedManifest(filePath: string): VerifiedManifest | null {
    try {
        return validateVerifiedManifest(readJsonFile<VerifiedManifest>(filePath));
    } catch {
        return null;
    }
}

export function buildFieldDecision(
    candidate: CandidateManifest,
    report: VerificationReport,
    verifiedBy: string,
    evidenceRef: string,
    options?: {
        onlyPaths?: ReadonlySet<string>;
    },
): FieldDecision {
    const candidateFields = flattenCandidateFields(candidate);
    const promoted: VerifiedField[] = [];
    const rejected: RejectedField[] = [];
    const onlyPaths = options?.onlyPaths;

    for (const [path, candidateField] of candidateFields.entries()) {
        const observations = report.scenarioResults.flatMap((scenarioResult) =>
            scenarioResult.fieldResults
                .filter((fieldResult) => fieldResult.path === path)
                .map((fieldResult) => ({
                    scenarioId: scenarioResult.scenarioId,
                    ogValue: fieldResult.ogValue,
                    pluginValue: fieldResult.pluginValue,
                    match: fieldResult.match,
                })),
        );

        if (observations.length === 0) {
            continue;
        }

        const mismatches = observations.filter((observation) => !observation.match);
        if (mismatches.length > 0) {
            rejected.push({
                path,
                candidateValue: candidateField.value,
                rejectionReason: "Observed OG/plugin mismatch during live verification",
                mismatches: mismatches.map((mismatch) => ({
                    scenarioId: mismatch.scenarioId,
                    expected: mismatch.ogValue,
                    actual: mismatch.pluginValue,
                })),
            });
            continue;
        }

        const distinctLiveValues = [
            ...new Set(observations.map((observation) => stableStringify(observation.ogValue))),
        ];
        if (distinctLiveValues.length !== 1) {
            rejected.push({
                path,
                candidateValue: candidateField.value,
                rejectionReason: "Live verification produced multiple values across scenarios",
                mismatches: observations.map((observation) => ({
                    scenarioId: observation.scenarioId,
                    expected: observation.ogValue,
                    actual: observation.pluginValue,
                })),
            });
            continue;
        }

        const liveValue = observations[0]?.ogValue;
        if (stableStringify(candidateField.value) !== stableStringify(liveValue)) {
            rejected.push({
                path,
                candidateValue: candidateField.value,
                rejectionReason: "Candidate manifest value does not match live verified value",
                mismatches: observations.map((observation) => ({
                    scenarioId: observation.scenarioId,
                    expected: liveValue,
                    actual: candidateField.value,
                })),
            });
            continue;
        }

        if (onlyPaths && onlyPaths.size > 0 && !onlyPaths.has(path)) {
            continue;
        }

        promoted.push({
            path,
            value: candidateField.value,
            verifiedAt: report.verifiedAt,
            verifiedBy,
            scenarioIds: [...new Set(observations.map((observation) => observation.scenarioId))].sort(),
            evidenceRef,
        });
    }

    return { promoted, rejected };
}

function mergeVerifiedManifest(
    existing: VerifiedManifest | null,
    input: {
        version: string;
        verifiedAt: string;
        verifiedBy: string;
        scenarioIds: string[];
        promotedFields: VerifiedField[];
        rejectedCandidateFields: RejectedField[];
        evidenceArtifacts: string[];
    },
): VerifiedManifest {
    const promotedByPath = new Map<string, VerifiedField>();
    for (const field of existing?.promotedFields ?? []) {
        promotedByPath.set(field.path, field);
    }
    for (const field of input.promotedFields) {
        promotedByPath.set(field.path, field);
    }

    const rejectedByPath = new Map<string, RejectedField>();
    for (const field of existing?.rejectedCandidateFields ?? []) {
        rejectedByPath.set(field.path, field);
    }
    for (const field of input.rejectedCandidateFields) {
        rejectedByPath.set(field.path, field);
    }

    for (const promotedField of input.promotedFields) {
        rejectedByPath.delete(promotedField.path);
    }

    return {
        version: input.version,
        verifiedAt: input.verifiedAt,
        verifiedBy: input.verifiedBy,
        scenarioIds: [...new Set([...(existing?.scenarioIds ?? []), ...input.scenarioIds])].sort(),
        promotedFields: [...promotedByPath.values()].sort((left, right) => left.path.localeCompare(right.path)),
        rejectedCandidateFields: [...rejectedByPath.values()].sort((left, right) =>
            left.path.localeCompare(right.path),
        ),
        evidenceArtifacts: [...new Set([...(existing?.evidenceArtifacts ?? []), ...input.evidenceArtifacts])].sort(),
    };
}

function updateIndex(indexPath: string, version: string, manifestPath: string, timestamp: string): ManifestIndex {
    const currentIndex = (() => {
        try {
            return readJsonFile<ManifestIndex>(indexPath);
        } catch {
            return createEmptyIndex(timestamp);
        }
    })();

    const versions = currentIndex.versions.filter((entry) => entry.version !== version);
    const nextEntry: ManifestIndexEntry = {
        version,
        path: manifestPath,
        createdAt: timestamp,
    };
    versions.push(nextEntry);
    versions.sort((left, right) => compareVersions(left.version, right.version));

    return {
        schemaVersion: currentIndex.schemaVersion || "1.0.0",
        lastUpdated: timestamp,
        versions,
        latest: versions.length > 0 ? (versions[versions.length - 1]?.version ?? null) : null,
    };
}

function writeJson(filePath: string, value: unknown): void {
    mkdirSync(dirname(filePath), { recursive: true });
    writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

async function main(): Promise<void> {
    const args = parseArgs(process.argv.slice(2));
    if (args.help) {
        printUsage();
        return;
    }

    const candidate = validateCandidateManifest(readJsonFile<CandidateManifest>(args.candidatePath));
    const report = readJsonFile<VerificationReport>(args.reportPath);

    if (candidate.version !== args.version) {
        throw new Error(`Candidate manifest version ${candidate.version} does not match --version ${args.version}`);
    }
    if (report.version !== args.version) {
        throw new Error(`Verification report version ${report.version} does not match --version ${args.version}`);
    }

    const verifiedBy = args.verifiedBy ?? report.verifiedBy;
    const relativeEvidenceRef = args.reportPath.startsWith(REPO_ROOT)
        ? args.reportPath.slice(REPO_ROOT.length + 1)
        : args.reportPath;
    const verifiedManifestPath = resolve(args.verifiedDir, `${args.version}.json`);
    const existing = readExistingVerifiedManifest(verifiedManifestPath);
    const filteredDecision = buildFieldDecision(candidate, report, verifiedBy, relativeEvidenceRef, {
        onlyPaths: args.onlyPaths,
    });
    const mergedManifest = mergeVerifiedManifest(existing, {
        version: args.version,
        verifiedAt: report.verifiedAt,
        verifiedBy,
        scenarioIds: report.scenarioResults.map((scenarioResult) => scenarioResult.scenarioId),
        promotedFields: filteredDecision.promoted,
        rejectedCandidateFields: filteredDecision.rejected,
        evidenceArtifacts: [relativeEvidenceRef],
    });

    writeJson(verifiedManifestPath, mergedManifest);

    const relativeManifestPath = verifiedManifestPath.startsWith(REPO_ROOT)
        ? verifiedManifestPath.slice(REPO_ROOT.length + 1)
        : verifiedManifestPath;
    const indexPath = resolve(args.verifiedDir, "index.json");
    const index = updateIndex(indexPath, args.version, relativeManifestPath, report.verifiedAt);
    writeJson(indexPath, index);

    console.log(
        JSON.stringify(
            {
                version: args.version,
                promotedFields: filteredDecision.promoted.map((field) => field.path),
                rejectedFields: filteredDecision.rejected.map((field) => ({
                    path: field.path,
                    reason: field.rejectionReason,
                })),
                verifiedManifestPath,
                indexPath,
            },
            null,
            2,
        ),
    );
}

if (import.meta.main) {
    main().catch((error) => {
        console.error(`Error: ${error instanceof Error ? error.message : String(error)}`);
        process.exit(1);
    });
}
